example:
  property: "test example property test"
spring:
  datasource:
    username: root
    password: "{cipher}7c49172ec471199116c0f5dfc5250b1780d2e603ab74c762c2fd996077e90cc5"
    url: jdbc:mysql://localhost:3306/spring_cloud_demo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
