example:
  property: "test example property test"
spring:
  datasource:
    name: spring_cloud_demo
    username: root
    password: {cipher}e322e857857318856d2678ff510c55f740214eb5696573a37bae1d868468148b
    url: jdbc:mysql://localhost:3306
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
